import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  compatibilityJSON: "v3",
  resources: {
    en: {
      translation: {
        greeting: "Hello!",
        profileTitle: "Profile",
        products: "PRODUCTS",
        password: "Password",
        email: "Email",
        login: "Login",
        loading: "Loading...",
        rating: "Rating",
        searching: "Searching...",
        search: "Search...",
        model: "Model",
        productDescription: "Product Description",
        productCategory: "Product Category",
        brand: "Brand",
        home: "Home",
        favorites: "Favorites",
        settings: "Settings",
        categories: "Categories",
        productDetail: "Product Detail",
        noResults: "No results found.",
        smartphones: "Smartphones",
        laptops: "Laptops",
        fragrances: "Fragrances",
        skincare: "Skincare",
        groceries: "Groceries",
        "home-decoration": "Home Decoration",
        furniture: "Furniture",
        tops: "Tops",
        "womens-dresses": "Women's Dresses",
        "womens-shoes": "Women's Shoes",
        "mens-shirts": "Men's Shirts",
        "mens-shoes": "Men's Shoes",
        "mens-watches": "Men's Watches",
        "womens-watches": "Women's Watches",
        "womens-bags": "Women's Bags",
        "womens-jewellery": "Women's Jewellery",
        sunglasses: "Sunglasses",
        automotive: "Automotive",
        motorcycle: "Motorcycle",
        lighting: "Lighting",
        changeTheLanguage: "Change Language",
        english: "English",
        turkish: "Turkish",
        changesApplicationLanguage: "Changes application language",
        logOut: "Log Out",
        confirmLogoutMessage: "Are you sure you want to log out?",
        cancel: "Cancel",
        confirm: "Confirm",
        noFavProducts: "You have no favorite products.",
      },
    },
    tr: {
      translation: {
        greeting: "Merhaba!",
        profileTitle: "Profil",
        products: "ÜRÜNLER",
        password: "Şifre",
        email: "Eposta",
        login: "Giriş Yap",
        loading: "Yükleniyor...",
        rating: "Puan",
        searching: "Aranıyor...",
        search: "Arama...",
        model: "Model",
        productDescription: "Ürün Açıklaması",
        productCategory: "Ürün Kategorisi",
        brand: "Üretici",
        home: "Anasayfa",
        favorites: "Favoriler",
        settings: "Ayarlar",
        categories: "Kategoriler",
        productDetail: "Ürün Detayı",
        noResults: "Sonuç bulunamadı.",
        smartphones: "Akıllı Telefonlar",
        laptops: "Dizüstü Bilgisayarlar",
        fragrances: "Parfümler",
        skincare: "Cilt Bakımı",
        groceries: "Market Alışverişi",
        "home-decoration": "Ev Dekorasyonu",
        furniture: "Mobilya",
        tops: "Üst Giyim",
        "womens-dresses": "Kadın Elbiseleri",
        "womens-shoes": "Kadın Ayakkabıları",
        "mens-shirts": "Erkek Gömlekleri",
        "mens-shoes": "Erkek Ayakkabıları",
        "mens-watches": "Erkek Saatleri",
        "womens-watches": "Kadın Saatleri",
        "womens-bags": "Kadın Çantaları",
        "womens-jewellery": "Kadın Takıları",
        sunglasses: "Güneş Gözlükleri",
        automotive: "Otomotiv",
        motorcycle: "Motorsiklet",
        lighting: "Aydınlatma",
        changeTheLanguage: "Dili Değiştir",
        english: "İngilizce",
        turkish: "Türkçe",
        changesApplicationLanguage: "Uygulama dilini değiştirir",
        logOut: "Çıkış Yap",
        confirmLogoutMessage: "Çıkış yapmak istediğinize emin misiniz?",
        cancel: "İptal",
        confirm: "Onayla",
        noFavProducts: "Favori ürününüz bulunmamaktadır.",
      },
    },
  },

  lng: "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
